version: '3'

services: 
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "80:80"
  nodeserver:
    build: 
      dockerfile: Dockerfile
      context: ./
    ports: 
      - "5000:5000"