version: '3'

services: 
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "8000:80"
  nodeserver:
    build: 
      dockerfile: Dockerfile
      context: ./
    depends_on: 
      - nginx
    ports: 
      - "5000"